language: csharp

os:
 - linux
 - osx

dist: bionic
osx_image: xcode9.1

mono: none
dotnet: 3.0.100

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ulimit -n 2048; fi
install:
  - dotnet tool install -g dotnet-format
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet-format --version
before_script:
  - echo "Checking format..." 
  - dotnet format --check --dry-run -w src/neo-vm -v diagnostic         # check C# formatting for the source
  - dotnet format --check --dry-run -w tests/neo-vm.Tests -v diagnostic # check C# formatting for the unit tests
  - cd tests/neo-vm.Tests
script:
  - dotnet restore
  - find * -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
  # After all tests OK, Send CodeDov report
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - bash <(curl -s https://codecov.io/bash) -v
