language: csharp

os:
 - linux
 - osx

dist: bionic
osx_image: xcode9.1

mono: none
dotnet: 3.0.100

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ulimit -n 2048; fi
before_script: |
    export COLLECT_COVERAGE=false
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Installing tools ...";
      dotnet tool install -g dotnet-format
      export PATH="$PATH:$HOME/.dotnet/tools"
      dotnet-format --version
      echo "Checking format ...";
      dotnet format --check --dry-run -w src/neo-vm -v diagnostic;         # check C# formatting for the source
      dotnet format --check --dry-run -w tests/neo-vm.Tests -v diagnostic; # check C# formatting for the unit tests
      export COLLECT_COVERAGE=true
    fi
script:
  - cd tests/neo-vm.Tests
  - dotnet restore
  - find * -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
  - dotnet test /p:CollectCoverage=$COLLECT_COVERAGE /p:CoverletOutputFormat=opencover
after_success: |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      # After all tests OK, Send CodeDov report
      echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
      bash <(curl -s https://codecov.io/bash) -v
    fi
