name: .NET Core Test and Publish

on:
  push:

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Chectout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Check format
      run: |
        dotnet tool install --tool-path ./ dotnet-format
        ./dotnet-format --check --dry-run -v diagnostic
    - name: Test
      run: |
        find tests -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=${GITHUB_WORKSPACE}/coverage/lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  PublishGithub:
    if: true || github.ref == 'refs/heads/master' && startsWith(github.repository, 'neo-project/')
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Chectout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1
    - name: Pack with dotnet
      run: git rev-list --count HEAD |xargs printf "CI%05d" |xargs dotnet pack -c Debug -o out --include-source --version-suffix
    - name: Publish to Github Packages
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/neo-project/index.json" -UserName neo-project -Password ${GITHUB_TOKEN}
        nuget push out/*.nupkg -Source "GitHub"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  PublishMyGet:
    if: true || github.ref == 'refs/heads/master' && startsWith(github.repository, 'neo-project/')
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Chectout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Pack with dotnet
      run: git rev-list --count HEAD |xargs printf "CI%05d" |xargs dotnet pack -c Debug -o out --include-source --version-suffix
    - name: Publish to MyGet
      run: dotnet nuget push out/*.nupkg -s https://www.myget.org/F/neo/ -ss https://www.myget.org/F/neo/symbols/ -k ${MYGET_TOKEN} -sk ${MYGET_TOKEN}
      env:
        MYGET_TOKEN: ${{ secrets.MYGET_TOKEN }}
