name: .NET Core

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Check format
      run: dotnet format --check --dry-run -v diagnostic
    - name: Test
      run: dotnet test
