name: Publish

on: push

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Chectout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Pack with dotnet
      run: dotnet pack -c Debug -o out --version-suffix CI$(date +%s)
